/*
 ctreesitter_mufi.c
 Placeholder implementation of the C API for the Tree-sitter Mufi integration.

 This file provides lightweight stubs so the Swift side can link against a stable
 C interface even when a generated Tree-sitter parser is not present. The real
 parser (generated by the Tree-sitter CLI) will replace or augment these stubs
 with proper parsing/highlighting behavior.

 The functions intentionally report \"not available\" semantics (parser not present)
 and perform no highlighting so the editor can safely fall back to the regex-based
 highlighter while the full Tree-sitter integration is being generated/installed.
 */

#include <CTreeSitterMufi/ctreesitter_mufi.h>
#include <string.h>
#include <stdint.h>
#include "tree_sitter/api.h"
#include "tree_sitter/parser.h"
#include <stdlib.h>

// Forward declaration for the generated language accessor
extern const TSLanguage *tree_sitter_mufi(void);

// Embedded highlights query (from third_party/tree-sitter-mufi/queries/highlights.scm)
static const char *mufi_highlights_query =
  "((comment) @comment)\n"
  "\n"
  "((string) @string.quoted.double)\n"
  "\n"
  "((number) @constant.numeric)\n"
  "\n"
  "((identifier) @keyword\n"
  " (#match? @keyword \"^(and|class|else|false|for|fun|if|let|nil|or|print|return|self|super|true|var|while)$\"))\n"
  "\n"
  "((call_expression\n"
  "  (identifier) @builtin.function\n"
  "  (#match? @builtin.function \"^(assert|array|linked_list|hash_table|matrix|fvec|range|linspace|slice|splice|push|pop|push_front|pop_front|nth|sort|contains|insert|len|search|is_empty|equal_list|reverse|merge|clone|clear|put|get|remove|set_row|set_col|set|kolasa|rref|rank|transpose|det|lu|workspace|interp1|sum|mean|std|vari|maxl|minl|dot|cross|norm|angle|proj|reflect|reject|refract|what_is|input|double|int|str|ln|log2|log10|pi|sin|cos|tan|asin|acos|atan|complex|abs|phase|sfc|rand|randn|pow|sqrt|ceil|floor|round|max|min|create_file|read_file|write_file|delete_file|create_dir|delete_dir|now|now_ns|now_ms|get_req|post_req|put_req|del_req|open)$\"))))\n"
  "\n"
  "((function_declaration\n"
  "  (identifier) @function.definition))\n"
  "\n"
  "((variable_declaration\n"
  "  (identifier) @variable.definition))\n"
  "\n"
  "((identifier) @variable)\n";

// Map a query capture name (not null-terminated; name_len provided) to a cts_token_type.
static int32_t mufi_capture_to_token_type(const char *name, uint32_t name_len) {
    char buf[64];
    uint32_t n = name_len < (sizeof(buf) - 1) ? name_len : (sizeof(buf) - 1);
    memcpy(buf, name, n);
    buf[n] = '\0';

    if (strncmp(buf, "comment", 7) == 0) return CTS_TOKEN_COMMENT;
    if (strncmp(buf, "string", 6) == 0) return CTS_TOKEN_STRING;
    if (strcmp(buf, "number") == 0 || strstr(buf, "numeric") != NULL) return CTS_TOKEN_NUMBER;
    if (strncmp(buf, "keyword", 7) == 0) return CTS_TOKEN_KEYWORD;
    if (strstr(buf, "function") != NULL || strcmp(buf, "builtin.function") == 0) return CTS_TOKEN_FUNCTION;
    if (strncmp(buf, "variable", 8) == 0) return CTS_TOKEN_IDENTIFIER;
    return CTS_TOKEN_UNKNOWN;
}

int cts_mufi_parser_available(void) {
    // Return non-zero when the generated language is available (linked in).
    const TSLanguage *lang = tree_sitter_mufi();
    return (lang != NULL) ? 1 : 0;
}

int cts_mufi_highlight_ranges(
    const char *text,
    void (*callback)(int32_t start, int32_t length, int32_t tokenType, void *ctx),
    void *ctx
) {
    // Validate inputs
    if (text == NULL || callback == NULL) {
        return -1;
    }

    // Ensure the generated language is present
    const TSLanguage *lang = tree_sitter_mufi();
    if (lang == NULL) {
        return -1;
    }

    // Create a parser and parse the provided UTF-8 text
    TSParser *parser = ts_parser_new();
    if (!parser) {
        return -1;
    }
    ts_parser_set_language(parser, lang);

    TSTree *tree = ts_parser_parse_string(parser, NULL, text, (uint32_t)strlen(text));
    if (tree == NULL) {
        ts_parser_delete(parser);
        return -1;
    }

    // Compile the highlights query
    uint32_t error_offset = 0;
    TSQueryError error_type = 0;
    TSQuery *query = ts_query_new(lang, mufi_highlights_query, (uint32_t)strlen(mufi_highlights_query), &error_type, &error_offset);
    if (query == NULL) {
        ts_tree_delete(tree);
        ts_parser_delete(parser);
        return -1;
    }

    // Execute the query against the parse tree
    TSQueryCursor *cursor = ts_query_cursor_new();
    ts_query_cursor_exec(cursor, query, ts_tree_root_node(tree));

    TSQueryMatch match;
    int32_t reported = 0;

    while (ts_query_cursor_next_match(cursor, &match)) {
        for (uint32_t i = 0; i < match.capture_count; i++) {
            TSQueryCapture capture = match.captures[i];
            uint32_t name_len = 0;
            const char *name = ts_query_capture_name_for_id(query, capture.index, &name_len);
            int32_t tokenType = mufi_capture_to_token_type(name, name_len);

            uint32_t start = ts_node_start_byte(capture.node);
            uint32_t end = ts_node_end_byte(capture.node);
            int32_t length = (int32_t)(end - start);

            // Invoke the callback with byte offsets (UTF-8)
            callback((int32_t)start, length, tokenType, ctx);
            reported++;
        }
    }

    // Cleanup
    ts_query_cursor_delete(cursor);
    ts_query_delete(query);
    ts_tree_delete(tree);
    ts_parser_delete(parser);

    return reported;
}