/*
 ctreesitter_mufi.c
 Placeholder implementation of the C API for the Tree-sitter Mufi integration.

 This file provides lightweight stubs so the Swift side can link against a stable
 C interface even when a generated Tree-sitter parser is not present. The real
 parser (generated by the Tree-sitter CLI) will replace or augment these stubs
 with proper parsing/highlighting behavior.

 The functions intentionally report \"not available\" semantics (parser not present)
 and perform no highlighting so the editor can safely fall back to the regex-based
 highlighter while the full Tree-sitter integration is being generated/installed.
 */

#include <CTreeSitterMufi/ctreesitter_mufi.h>
#include <string.h>
#include <stdint.h>
#include "tree_sitter/api.h"
#include "tree_sitter/parser.h"
#include <stdlib.h>
#include <pthread.h>

// Forward declaration for the generated language accessor
extern const TSLanguage *tree_sitter_mufi(void);

// Embedded highlights query (from third_party/tree-sitter-mufi/queries/highlights.scm)
static const char *mufi_highlights_query =
  "((comment) @comment)\n"
  "\n"
  "((string) @string.quoted.double)\n"
  "\n"
  "((number) @constant.numeric)\n"
  "\n"
  "((identifier) @keyword\n"
  " (#match? @keyword \"^(and|class|else|false|for|fun|if|let|nil|or|print|return|self|super|true|var|while)$\"))\n"
  "\n"
  "((call_expression\n"
  "  (identifier) @builtin.function\n"
  "  (#match? @builtin.function \"^(assert|array|linked_list|hash_table|matrix|fvec|range|linspace|slice|splice|push|pop|push_front|pop_front|nth|sort|contains|insert|len|search|is_empty|equal_list|reverse|merge|clone|clear|put|get|remove|set_row|set_col|set|kolasa|rref|rank|transpose|det|lu|workspace|interp1|sum|mean|std|vari|maxl|minl|dot|cross|norm|angle|proj|reflect|reject|refract|what_is|input|double|int|str|ln|log2|log10|pi|sin|cos|tan|asin|acos|atan|complex|abs|phase|sfc|rand|randn|pow|sqrt|ceil|floor|round|max|min|create_file|read_file|write_file|delete_file|create_dir|delete_dir|now|now_ns|now_ms|get_req|post_req|put_req|del_req|open)$\"))))\n"
  "\n"
  "((function_declaration\n"
  "  (identifier) @function.definition))\n"
  "\n"
  "((variable_declaration\n"
  "  (identifier) @variable.definition))\n"
  "\n"
  "((identifier) @variable)\n";

// Map a query capture name (not null-terminated; name_len provided) to a cts_token_type.
static int32_t mufi_capture_to_token_type(const char *name, uint32_t name_len) {
    char buf[64];
    uint32_t n = name_len < (sizeof(buf) - 1) ? name_len : (sizeof(buf) - 1);
    memcpy(buf, name, n);
    buf[n] = '\0';

    if (strncmp(buf, "comment", 7) == 0) return CTS_TOKEN_COMMENT;
    if (strncmp(buf, "string", 6) == 0) return CTS_TOKEN_STRING;
    if (strcmp(buf, "number") == 0 || strstr(buf, "numeric") != NULL) return CTS_TOKEN_NUMBER;
    if (strncmp(buf, "keyword", 7) == 0) return CTS_TOKEN_KEYWORD;
    if (strstr(buf, "function") != NULL || strcmp(buf, "builtin.function") == 0) return CTS_TOKEN_FUNCTION;
    if (strncmp(buf, "variable", 8) == 0) return CTS_TOKEN_IDENTIFIER;
    return CTS_TOKEN_UNKNOWN;
}

static TSParser *g_parser = NULL;
static TSQuery *g_query = NULL;
static pthread_mutex_t g_parser_mutex = PTHREAD_MUTEX_INITIALIZER;
static int g_atexit_registered = 0;

static void cts_mufi_runtime_cleanup(void);

// Ensure the cached parser and compiled query are initialized.
// Returns 0 on success, -1 on failure.
static int ensure_parser_and_query(void) {
    // Fast check without locking
    if (g_parser != NULL && g_query != NULL) return 0;

    // Lock and initialize if necessary
    pthread_mutex_lock(&g_parser_mutex);

    if (g_parser != NULL && g_query != NULL) {
        pthread_mutex_unlock(&g_parser_mutex);
        return 0;
    }

    const TSLanguage *lang = tree_sitter_mufi();
    if (lang == NULL) {
        pthread_mutex_unlock(&g_parser_mutex);
        return -1;
    }

    TSParser *parser = ts_parser_new();
    if (!parser) {
        pthread_mutex_unlock(&g_parser_mutex);
        return -1;
    }

    if (!ts_parser_set_language(parser, lang)) {
        ts_parser_delete(parser);
        pthread_mutex_unlock(&g_parser_mutex);
        return -1;
    }

    uint32_t q_error_offset = 0;
    TSQueryError qerr = TSQueryErrorNone;
    TSQuery *query = ts_query_new(lang, mufi_highlights_query, (uint32_t)strlen(mufi_highlights_query), &qerr, &q_error_offset);
    if (!query) {
        ts_parser_delete(parser);
        pthread_mutex_unlock(&g_parser_mutex);
        return -1;
    }

    // Publish initialized objects
    g_parser = parser;
    g_query = query;

    if (!g_atexit_registered) {
        atexit(cts_mufi_runtime_cleanup);
        g_atexit_registered = 1;
    }

    pthread_mutex_unlock(&g_parser_mutex);
    return 0;
}

// Cleanup cached runtime objects at library unload
static void cts_mufi_runtime_cleanup(void) {
    pthread_mutex_lock(&g_parser_mutex);
    if (g_query) {
        ts_query_delete(g_query);
        g_query = NULL;
    }
    if (g_parser) {
        ts_parser_delete(g_parser);
        g_parser = NULL;
    }
    pthread_mutex_unlock(&g_parser_mutex);

    // Destroy the mutex - it is safe here since program is terminating
    pthread_mutex_destroy(&g_parser_mutex);
}

int cts_mufi_parser_available(void) {
    return (ensure_parser_and_query() == 0) ? 1 : 0;
}

int cts_mufi_highlight_ranges(
    const char *text,
    void (*callback)(int32_t start, int32_t length, int32_t tokenType, void *ctx),
    void *ctx
) {
    // Validate inputs
    if (text == NULL || callback == NULL) {
        return -1;
    }

    // Ensure parser & query are initialized
    if (ensure_parser_and_query() != 0) {
        return -1;
    }

    // Parse using the cached parser (protected by the mutex)
    pthread_mutex_lock(&g_parser_mutex);
    TSTree *tree = ts_parser_parse_string(g_parser, NULL, text, (uint32_t)strlen(text));
    pthread_mutex_unlock(&g_parser_mutex);

    if (tree == NULL) {
        return -1;
    }

    // Execute the precompiled (cached) query against the parse tree
    TSQueryCursor *cursor = ts_query_cursor_new();
    ts_query_cursor_exec(cursor, g_query, ts_tree_root_node(tree));

    TSQueryMatch match;
    int32_t reported = 0;

    while (ts_query_cursor_next_match(cursor, &match)) {
        for (uint32_t i = 0; i < match.capture_count; i++) {
            TSQueryCapture capture = match.captures[i];
            uint32_t name_len = 0;
            const char *name = ts_query_capture_name_for_id(g_query, capture.index, &name_len);
            int32_t tokenType = mufi_capture_to_token_type(name, name_len);

            uint32_t start = ts_node_start_byte(capture.node);
            uint32_t end = ts_node_end_byte(capture.node);
            int32_t length = (int32_t)(end - start);

            // Invoke the callback with byte offsets and length
            callback((int32_t)start, length, tokenType, ctx);
            reported++;
        }
    }

    // cleanup tree & cursor (cached query and parser remain)
    ts_query_cursor_delete(cursor);
    ts_tree_delete(tree);

    return reported;
}